### ISSUE TITLE
fatal error C1056 happens occasionally when compiling onig-sys/oniguruma/src

### ISSUE THREAD

**Issue by sepcnt** [rust-onig/rust-onig#189]
Build with `rustc 1.80.1 (3f5fd8dd4 2024-08-06)` and `cl 19.41.34120`. 
Simplely add `onig-sys` to an empty project could reproduce the problem.
However this error is probabilistic.

```log
regexec.c
  regerror.c
  regparse.c
  regext.c
  regcomp.c
  ~\.cargo\registry\src\[registry]\onig_sys-69.8.1\oniguruma\src\regcomp.c : fatal error C1056: cannot update the time date stamp field in '[project]\target\debug\build\onig_sys-3296a77ff32ef0a9\out\abd886268342579b-regcomp.o'; error code %u

  --- stderr


  error occurred: Command "[Visual Studio]\\VC\\Tools\\MSVC\\14.41.34120\\bin\\HostX64\\x64\\cl.exe" "-nologo" "-MD" "-Z7" "-Brepro" "-I" "[project]\\target\\debug\\build\\onig_sys-3296a77ff32ef0a9\\out" "-I" "oniguruma\\src" "-Fo[project]\\src-tauri\\target\\debug\\build\\onig_sys-3296a77ff32ef0a9\\out\\abd886268342579b-regcomp.o" "-c" "oniguruma\\src\\regcomp.c" with args cl.exe did not execute successfully (status code exit code: 2).
```
