### ISSUE TITLE
onig v4.3.1 fails to build with rust 1.27.0

### ISSUE THREAD

**Issue by rivy** [rust-onig/rust-onig#97]
Compilation is broken for rust v1.27.0 with v4.3.1...

```
   Compiling onig v4.3.1
error[E0658]: access to extern crates through prelude is experimental (see issue #44660)
   --> C:\Users\appveyor\.cargo\registry\src\github.com-1ecc6299db9ec823\onig-4.3.1\src\find.rs:180:43
    |
180 |                 (&mut region.raw) as *mut onig_sys::OnigRegion,
    |                                           ^^^^^^^^
error: aborting due to previous error
For more information about this error, try `rustc --explain E0658`.
error: Could not compile `onig`.
```

A month ago, v4.2.1 compiled and worked without error.

I think a minimum rust compiler version change should mean a semver major version increment (not just a minor), so that builds don't just arbitrarily break on re-build.

I also can't find any indication for minimum rust version in your code, docs, or CI.

Thanks for your attention.

**Comment by iwillspeak** [comment]
Thanks for this report. Unfortunately this crate hasn't had a very grown up policy towards minimum Rust version so far. It should do though. I can see two ways to solve this:

Treat compiler version as major brekaing change:
 * Document the crate's minimum supported `rustc` version
 * Publish a new major version with the same codebase
 * Publish a new minor version which rolls Rust support back to 1.27
 * Include a test compile wtih our stated minimum `rustc` version in CI

Treat compiler version as minior brekaing change:
 * Document the crate's minimum supported `rustc` version
 * Include a test compile with our stated minimum `rustc` version in CI

I had kind of always assumed people depended on crates with `x.y` version numbers and that compiler version changes were treated as minor version breaking changes in the Rust ecosystem. This appears to be BurntSushi's oppinion over on https://users.rust-lang.org/t/rust-version-requirement-change-as-semver-breaking-or-not/20980 (https://github.com/rust-lang/regex#minimum-rust-version-policy).

**Comment by iwillspeak** [comment]
This should now be fixed by #98.

**Comment by rivy** [comment]
Thanks for the quick response!
